"""Type stubs for the pubgrub_py._core Rust extension module."""

class Resolver:
    """PubGrub dependency resolver.

    A resolver that uses the PubGrub algorithm to find a compatible set of
    package versions satisfying all dependency constraints.

    Example:
        >>> resolver = Resolver()
        >>> resolver.add_package("foo", "1.0.0", {"bar": ">=2.0.0"})
        >>> resolver.add_package("bar", "2.0.0")
        >>> resolver.resolve({"foo": ">=1.0.0"})
        {"foo": "1.0.0", "bar": "2.0.0"}
    """

    def __init__(self) -> None:
        """Create a new resolver instance."""
        ...

    def add_package(
        self,
        name: str,
        version: str,
        dependencies: dict[str, str] | None = None,
    ) -> None:
        """Add a package with its version and dependencies.

        Args:
            name: Package identifier.
            version: Version string (semver format: X.Y.Z).
            dependencies: Dict of {package: constraint} e.g. {"foo": ">=1.0.0,<2.0.0"}.

        Raises:
            ValueError: If version or constraint format is invalid.
        """
        ...

    def resolve(self, requirements: dict[str, str]) -> dict[str, str]:
        """Resolve dependencies starting from root packages.

        Args:
            requirements: Dict of {package: constraint} for root dependencies.

        Returns:
            Dict of {package: version} for all resolved packages.

        Raises:
            ResolutionError: If no valid solution exists (with explanation).
            ValueError: If a constraint format is invalid.
        """
        ...

class ResolutionError(Exception):
    """Raised when dependency resolution fails.

    Contains a human-readable explanation of why the resolution failed,
    generated by PubGrub's conflict reporter.
    """

    ...
